# Generated by Django 2.0.2 on 2018-03-12 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='features',
            options={'verbose_name': 'Features', 'verbose_name_plural': 'Features'},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='venue',
        ),
    ]
