# Generated by Django 2.0.2 on 2018-04-06 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0005_document_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='room',
        ),
    ]
