# Generated by Django 2.0.2 on 2018-04-07 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0008_room_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='owner',
        ),
    ]
