# Generated by Django 2.0.2 on 2018-04-13 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0010_room_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='venue',
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
    ]
