# Generated by Django 2.0.2 on 2018-04-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0011_auto_20180413_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a venue name', max_length=200)),
                ('address', models.CharField(help_text='Enter the address', max_length=200)),
            ],
            options={
                'permissions': (('can_edit_venue', 'Edit a venue details'),),
            },
        ),
    ]
