# Generated by Django 2.0.2 on 2018-04-15 20:34

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0015_auto_20180415_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a venue name', max_length=200, null=True)),
                ('address', models.CharField(help_text='Enter the address', max_length=200, null=True)),
                ('position', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'permissions': (('can_edit_venue', 'Edit a venue details'),),
            },
        ),
    ]
