# Generated by Django 2.0.2 on 2018-04-15 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0017_auto_20180415_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='position',
        ),
    ]
