# Generated by Django 2.0.2 on 2018-04-15 20:39

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0018_remove_venue_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='position',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
