# Generated by Django 2.0.2 on 2018-04-19 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0019_venue_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='House number', max_length=1024, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='venue',
            name='position',
        ),
        migrations.AddField(
            model_name='location',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookingapp.Venue'),
        ),
    ]
