# Generated by Django 2.0.2 on 2018-04-19 13:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0020_auto_20180419_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.CharField(help_text='Country', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='position',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='location',
            name='postcode',
            field=models.CharField(help_text='Postcode', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='street',
            field=models.CharField(help_text='Street name', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='town',
            field=models.CharField(help_text='Town', max_length=1024, null=True),
        ),
    ]
