# Generated by Django 2.0.2 on 2018-04-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0022_auto_20180425_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='country',
        ),
        migrations.AddField(
            model_name='location',
            name='county',
            field=models.CharField(help_text='County', max_length=1024, null=True),
        ),
    ]
